"""
SQLAlchemy Database Models for LinkedInsight.

This module defines all database models using SQLAlchemy's declarative base.
The models represent the core entities in the LinkedInsight system:

- User: Stores user profiles and their current skills
- SavedRoadmap: Stores AI-generated learning roadmaps for users
- JobPostMeta: Stores metadata about job postings (complements vector store)

All models use SQLAlchemy's declarative syntax and include proper relationships,
constraints, and helper methods.
"""

from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, JSON
from sqlalchemy.orm import relationship
from datetime import datetime
from app.db.sql import Base


class User(Base):
    """
    User model representing a LinkedInsight user.
    
    Stores user profile information including their current skills and career goals.
    This model serves as the foundation for personalization features.
    
    **Fields:**
    - id: Primary key, auto-incrementing integer
    - name: User's full name
    - email: User's email address (should be unique in production)
    - created_at: Timestamp when the user account was created
    - current_skills: JSON array of skills the user currently has
    - desired_roles: Comma-separated or JSON list of target job roles
    
    **Relationships:**
    - saved_roadmaps: One-to-many relationship with SavedRoadmap
    
    **Example:**
    ```python
    user = User(
        name="John Doe",
        email="john@example.com",
        current_skills=["Python", "SQL"],
        desired_roles="Data Scientist, Machine Learning Engineer"
    )
    db.add(user)
    db.commit()
    ```
    """
    __tablename__ = "users"
    
    # Primary key
    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    
    # User profile information
    name = Column(String(255), nullable=False, index=True, comment="User's full name")
    email = Column(String(255), nullable=False, unique=True, index=True, comment="User's email address")
    
    # Timestamp
    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
        comment="Account creation timestamp"
    )
    
    # Skills and career goals
    # Using JSON for flexibility - can store array of strings
    # In SQLite, JSON is stored as TEXT but can be queried as JSON
    current_skills = Column(
        JSON,
        nullable=True,
        comment="JSON array of user's current skills, e.g., ['Python', 'SQL', 'JavaScript']"
    )
    
    # Desired roles - can be JSON array or comma-separated string
    desired_roles = Column(
        Text,
        nullable=True,
        comment="Target job roles, e.g., 'Data Scientist, ML Engineer' or JSON array"
    )
    
    # Relationships
    # One user can have many saved roadmaps
    saved_roadmaps = relationship("SavedRoadmap", back_populates="user", cascade="all, delete-orphan")
    
    def __repr__(self) -> str:
        """String representation of the User model."""
        return f"<User(id={self.id}, name='{self.name}', email='{self.email}')>"
    
    def to_dict(self) -> dict:
        """
        Convert User instance to dictionary.
        
        Useful for JSON serialization in API responses.
        
        Returns:
            dict: Dictionary representation of the user
        """
        return {
            "id": self.id,
            "name": self.name,
            "email": self.email,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "current_skills": self.current_skills,
            "desired_roles": self.desired_roles
        }


class SavedRoadmap(Base):
    """
    SavedRoadmap model for storing AI-generated learning roadmaps.
    
    Stores personalized learning roadmaps generated by the AI system for users.
    Each roadmap is associated with a user and contains the skills they need to learn
    and the generated roadmap text.
    
    **Fields:**
    - id: Primary key, auto-incrementing integer
    - user_id: Foreign key to User table
    - generated_at: Timestamp when the roadmap was generated
    - missing_skills: JSON array or comma-separated list of skills to learn
    - roadmap_text: Full text of the generated roadmap (Markdown format)
    
    **Relationships:**
    - user: Many-to-one relationship with User
    
    **Example:**
    ```python
    roadmap = SavedRoadmap(
        user_id=1,
        missing_skills=["Machine Learning", "Deep Learning"],
        roadmap_text="# 4-Week Learning Roadmap..."
    )
    db.add(roadmap)
    db.commit()
    ```
    """
    __tablename__ = "saved_roadmaps"
    
    # Primary key
    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    
    # Foreign key to User
    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Reference to the user who owns this roadmap"
    )
    
    # Timestamp
    generated_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
        index=True,
        comment="Timestamp when the roadmap was generated"
    )
    
    # Roadmap data
    # Missing skills - can be JSON array or comma-separated string
    missing_skills = Column(
        Text,
        nullable=False,
        comment="Skills the user needs to learn, e.g., JSON array or comma-separated"
    )
    
    # Full roadmap text (Markdown format from LLM)
    roadmap_text = Column(
        Text,
        nullable=False,
        comment="Full text of the generated learning roadmap in Markdown format"
    )
    
    # Relationships
    # Many roadmaps belong to one user
    user = relationship("User", back_populates="saved_roadmaps")
    
    def __repr__(self) -> str:
        """String representation of the SavedRoadmap model."""
        return f"<SavedRoadmap(id={self.id}, user_id={self.user_id}, generated_at='{self.generated_at}')>"
    
    def to_dict(self) -> dict:
        """
        Convert SavedRoadmap instance to dictionary.
        
        Returns:
            dict: Dictionary representation of the roadmap
        """
        return {
            "id": self.id,
            "user_id": self.user_id,
            "generated_at": self.generated_at.isoformat() if self.generated_at else None,
            "missing_skills": self.missing_skills,
            "roadmap_text": self.roadmap_text
        }


class JobPostMeta(Base):
    """
    JobPostMeta model for storing job posting metadata.
    
    This model stores structured metadata about job postings. It complements
    the vector database (ChromaDB) by providing SQL-based querying capabilities
    and persistent storage of job metadata.
    
    The `id` field matches the ID used in the vector store, enabling correlation
    between SQL metadata and vector embeddings.
    
    **Fields:**
    - id: Primary key, string matching vector store ID (MD5 hash)
    - title: Job title
    - company: Company name
    - location: Job location
    - extracted_skills: JSON object containing extracted skills from NLP processing
    - raw_description: Full raw job description text
    
    **Example:**
    ```python
    job_meta = JobPostMeta(
        id="abc123def456",
        title="Senior Software Engineer",
        company="Tech Corp",
        location="Seattle, WA",
        extracted_skills={"programming_languages": ["Python"], "technical_skills": ["AWS"]},
        raw_description="Looking for a Python developer..."
    )
    db.add(job_meta)
    db.commit()
    ```
    """
    __tablename__ = "job_post_meta"
    
    # Primary key - string ID matching vector store ID
    # This allows correlation between SQL metadata and vector embeddings
    id = Column(
        String(255),
        primary_key=True,
        index=True,
        comment="Unique job ID matching the vector store ID (MD5 hash)"
    )
    
    # Job information
    title = Column(
        String(500),
        nullable=False,
        index=True,
        comment="Job title"
    )
    
    company = Column(
        String(255),
        nullable=True,
        index=True,
        comment="Company name"
    )
    
    location = Column(
        String(255),
        nullable=True,
        index=True,
        comment="Job location (city, state, country, etc.)"
    )
    
    # Extracted skills from NLP processing
    # Stored as JSON for structured querying
    extracted_skills = Column(
        JSON,
        nullable=True,
        comment="JSON object containing extracted skills: {programming_languages: [...], technical_skills: [...], required_skills: [...]}"
    )
    
    # Raw job description
    raw_description = Column(
        Text,
        nullable=True,
        comment="Full raw job description text from the job posting"
    )
    
    def __repr__(self) -> str:
        """String representation of the JobPostMeta model."""
        return f"<JobPostMeta(id='{self.id}', title='{self.title}', company='{self.company}')>"
    
    def to_dict(self) -> dict:
        """
        Convert JobPostMeta instance to dictionary.
        
        Returns:
            dict: Dictionary representation of the job metadata
        """
        return {
            "id": self.id,
            "title": self.title,
            "company": self.company,
            "location": self.location,
            "extracted_skills": self.extracted_skills,
            "raw_description": self.raw_description
        }

